{{- if .Values.ingress.enabled }}
{{- $fullName := include "openvas.fullname" . -}}
---
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else -}}    
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "openvas.fullname" . }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  labels:
    {{- include "openvas.labels" . | nindent 4 }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      - backend:
          service:
            port:
              number: 80
            name: {{ include "openvas.fullname" $ }}-service
        path: /
        pathType: Prefix
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end -}}
